$('.owl-carousel').owlCarousel({
    items:4,
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        430:{
            items:2
        },
        817:{
            items:3
        },
        1300:{
            items:4
        }
    }
})