$('.owl-carousel').owlCarousel({
    items:4,
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        925:{
            items:2
        },
        1400:{
            items:3
        },
        1850:{
            items:4
        }
    }
})